FROM golang:1.23-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o ingest ./cmd/ingest

FROM gcr.io/distroless/static:nonroot

WORKDIR /app

COPY --from=builder /app/ingest /app/ingest

ENTRYPOINT ["/app/ingest"]